// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_protobuf.proto

package edu.usfca.cs.dfs.storage;

public final class StorageProtobuf {
  private StorageProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StoreChunkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StoreChunk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string writefilechunkName = 1;</code>
     */
    java.lang.String getWritefilechunkName();
    /**
     * <code>string writefilechunkName = 1;</code>
     */
    com.google.protobuf.ByteString
        getWritefilechunkNameBytes();

    /**
     * <code>int32 chunkId = 2;</code>
     */
    int getChunkId();

    /**
     * <code>bytes writechunkdata = 3;</code>
     */
    com.google.protobuf.ByteString getWritechunkdata();

    /**
     * <code>string hostName = 4;</code>
     */
    java.lang.String getHostName();
    /**
     * <code>string hostName = 4;</code>
     */
    com.google.protobuf.ByteString
        getHostNameBytes();

    /**
     * <code>string reqtypewrite = 5;</code>
     */
    java.lang.String getReqtypewrite();
    /**
     * <code>string reqtypewrite = 5;</code>
     */
    com.google.protobuf.ByteString
        getReqtypewriteBytes();
  }
  /**
   * Protobuf type {@code StoreChunk}
   */
  public  static final class StoreChunk extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StoreChunk)
      StoreChunkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoreChunk.newBuilder() to construct.
    private StoreChunk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoreChunk() {
      writefilechunkName_ = "";
      chunkId_ = 0;
      writechunkdata_ = com.google.protobuf.ByteString.EMPTY;
      hostName_ = "";
      reqtypewrite_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StoreChunk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              writefilechunkName_ = s;
              break;
            }
            case 16: {

              chunkId_ = input.readInt32();
              break;
            }
            case 26: {

              writechunkdata_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              hostName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              reqtypewrite_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StoreChunk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StoreChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.class, edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.Builder.class);
    }

    public static final int WRITEFILECHUNKNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object writefilechunkName_;
    /**
     * <code>string writefilechunkName = 1;</code>
     */
    public java.lang.String getWritefilechunkName() {
      java.lang.Object ref = writefilechunkName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        writefilechunkName_ = s;
        return s;
      }
    }
    /**
     * <code>string writefilechunkName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWritefilechunkNameBytes() {
      java.lang.Object ref = writefilechunkName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        writefilechunkName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNKID_FIELD_NUMBER = 2;
    private int chunkId_;
    /**
     * <code>int32 chunkId = 2;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    public static final int WRITECHUNKDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString writechunkdata_;
    /**
     * <code>bytes writechunkdata = 3;</code>
     */
    public com.google.protobuf.ByteString getWritechunkdata() {
      return writechunkdata_;
    }

    public static final int HOSTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object hostName_;
    /**
     * <code>string hostName = 4;</code>
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      }
    }
    /**
     * <code>string hostName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQTYPEWRITE_FIELD_NUMBER = 5;
    private volatile java.lang.Object reqtypewrite_;
    /**
     * <code>string reqtypewrite = 5;</code>
     */
    public java.lang.String getReqtypewrite() {
      java.lang.Object ref = reqtypewrite_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqtypewrite_ = s;
        return s;
      }
    }
    /**
     * <code>string reqtypewrite = 5;</code>
     */
    public com.google.protobuf.ByteString
        getReqtypewriteBytes() {
      java.lang.Object ref = reqtypewrite_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqtypewrite_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWritefilechunkNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, writefilechunkName_);
      }
      if (chunkId_ != 0) {
        output.writeInt32(2, chunkId_);
      }
      if (!writechunkdata_.isEmpty()) {
        output.writeBytes(3, writechunkdata_);
      }
      if (!getHostNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hostName_);
      }
      if (!getReqtypewriteBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, reqtypewrite_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWritefilechunkNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, writefilechunkName_);
      }
      if (chunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chunkId_);
      }
      if (!writechunkdata_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, writechunkdata_);
      }
      if (!getHostNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hostName_);
      }
      if (!getReqtypewriteBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, reqtypewrite_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk other = (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) obj;

      boolean result = true;
      result = result && getWritefilechunkName()
          .equals(other.getWritefilechunkName());
      result = result && (getChunkId()
          == other.getChunkId());
      result = result && getWritechunkdata()
          .equals(other.getWritechunkdata());
      result = result && getHostName()
          .equals(other.getHostName());
      result = result && getReqtypewrite()
          .equals(other.getReqtypewrite());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WRITEFILECHUNKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getWritefilechunkName().hashCode();
      hash = (37 * hash) + CHUNKID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId();
      hash = (37 * hash) + WRITECHUNKDATA_FIELD_NUMBER;
      hash = (53 * hash) + getWritechunkdata().hashCode();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostName().hashCode();
      hash = (37 * hash) + REQTYPEWRITE_FIELD_NUMBER;
      hash = (53 * hash) + getReqtypewrite().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StoreChunk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StoreChunk)
        edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StoreChunk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StoreChunk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.class, edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        writefilechunkName_ = "";

        chunkId_ = 0;

        writechunkdata_ = com.google.protobuf.ByteString.EMPTY;

        hostName_ = "";

        reqtypewrite_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StoreChunk_descriptor;
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk build() {
        edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk buildPartial() {
        edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk result = new edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk(this);
        result.writefilechunkName_ = writefilechunkName_;
        result.chunkId_ = chunkId_;
        result.writechunkdata_ = writechunkdata_;
        result.hostName_ = hostName_;
        result.reqtypewrite_ = reqtypewrite_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) {
          return mergeFrom((edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk other) {
        if (other == edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance()) return this;
        if (!other.getWritefilechunkName().isEmpty()) {
          writefilechunkName_ = other.writefilechunkName_;
          onChanged();
        }
        if (other.getChunkId() != 0) {
          setChunkId(other.getChunkId());
        }
        if (other.getWritechunkdata() != com.google.protobuf.ByteString.EMPTY) {
          setWritechunkdata(other.getWritechunkdata());
        }
        if (!other.getHostName().isEmpty()) {
          hostName_ = other.hostName_;
          onChanged();
        }
        if (!other.getReqtypewrite().isEmpty()) {
          reqtypewrite_ = other.reqtypewrite_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object writefilechunkName_ = "";
      /**
       * <code>string writefilechunkName = 1;</code>
       */
      public java.lang.String getWritefilechunkName() {
        java.lang.Object ref = writefilechunkName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          writefilechunkName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string writefilechunkName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWritefilechunkNameBytes() {
        java.lang.Object ref = writefilechunkName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          writefilechunkName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string writefilechunkName = 1;</code>
       */
      public Builder setWritefilechunkName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        writefilechunkName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string writefilechunkName = 1;</code>
       */
      public Builder clearWritefilechunkName() {
        
        writefilechunkName_ = getDefaultInstance().getWritefilechunkName();
        onChanged();
        return this;
      }
      /**
       * <code>string writefilechunkName = 1;</code>
       */
      public Builder setWritefilechunkNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        writefilechunkName_ = value;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public Builder setChunkId(int value) {
        
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public Builder clearChunkId() {
        
        chunkId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString writechunkdata_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes writechunkdata = 3;</code>
       */
      public com.google.protobuf.ByteString getWritechunkdata() {
        return writechunkdata_;
      }
      /**
       * <code>bytes writechunkdata = 3;</code>
       */
      public Builder setWritechunkdata(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        writechunkdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes writechunkdata = 3;</code>
       */
      public Builder clearWritechunkdata() {
        
        writechunkdata_ = getDefaultInstance().getWritechunkdata();
        onChanged();
        return this;
      }

      private java.lang.Object hostName_ = "";
      /**
       * <code>string hostName = 4;</code>
       */
      public java.lang.String getHostName() {
        java.lang.Object ref = hostName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hostName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        java.lang.Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostName = 4;</code>
       */
      public Builder setHostName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hostName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 4;</code>
       */
      public Builder clearHostName() {
        
        hostName_ = getDefaultInstance().getHostName();
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 4;</code>
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hostName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reqtypewrite_ = "";
      /**
       * <code>string reqtypewrite = 5;</code>
       */
      public java.lang.String getReqtypewrite() {
        java.lang.Object ref = reqtypewrite_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqtypewrite_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reqtypewrite = 5;</code>
       */
      public com.google.protobuf.ByteString
          getReqtypewriteBytes() {
        java.lang.Object ref = reqtypewrite_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqtypewrite_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqtypewrite = 5;</code>
       */
      public Builder setReqtypewrite(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqtypewrite_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqtypewrite = 5;</code>
       */
      public Builder clearReqtypewrite() {
        
        reqtypewrite_ = getDefaultInstance().getReqtypewrite();
        onChanged();
        return this;
      }
      /**
       * <code>string reqtypewrite = 5;</code>
       */
      public Builder setReqtypewriteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqtypewrite_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StoreChunk)
    }

    // @@protoc_insertion_point(class_scope:StoreChunk)
    private static final edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk();
    }

    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StoreChunk>
        PARSER = new com.google.protobuf.AbstractParser<StoreChunk>() {
      public StoreChunk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StoreChunk(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StoreChunk> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StoreChunk> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RetrieveFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RetrieveFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string readfileName = 1;</code>
     */
    java.lang.String getReadfileName();
    /**
     * <code>string readfileName = 1;</code>
     */
    com.google.protobuf.ByteString
        getReadfileNameBytes();

    /**
     * <code>bytes readchunkdata = 2;</code>
     */
    com.google.protobuf.ByteString getReadchunkdata();

    /**
     * <code>string hostName = 3;</code>
     */
    java.lang.String getHostName();
    /**
     * <code>string hostName = 3;</code>
     */
    com.google.protobuf.ByteString
        getHostNameBytes();

    /**
     * <code>int32 chunkId = 4;</code>
     */
    int getChunkId();

    /**
     * <code>string reqtyperead = 5;</code>
     */
    java.lang.String getReqtyperead();
    /**
     * <code>string reqtyperead = 5;</code>
     */
    com.google.protobuf.ByteString
        getReqtypereadBytes();
  }
  /**
   * Protobuf type {@code RetrieveFile}
   */
  public  static final class RetrieveFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RetrieveFile)
      RetrieveFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RetrieveFile.newBuilder() to construct.
    private RetrieveFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RetrieveFile() {
      readfileName_ = "";
      readchunkdata_ = com.google.protobuf.ByteString.EMPTY;
      hostName_ = "";
      chunkId_ = 0;
      reqtyperead_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RetrieveFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              readfileName_ = s;
              break;
            }
            case 18: {

              readchunkdata_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              hostName_ = s;
              break;
            }
            case 32: {

              chunkId_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              reqtyperead_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_RetrieveFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_RetrieveFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.class, edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.Builder.class);
    }

    public static final int READFILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object readfileName_;
    /**
     * <code>string readfileName = 1;</code>
     */
    public java.lang.String getReadfileName() {
      java.lang.Object ref = readfileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readfileName_ = s;
        return s;
      }
    }
    /**
     * <code>string readfileName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReadfileNameBytes() {
      java.lang.Object ref = readfileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readfileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int READCHUNKDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString readchunkdata_;
    /**
     * <code>bytes readchunkdata = 2;</code>
     */
    public com.google.protobuf.ByteString getReadchunkdata() {
      return readchunkdata_;
    }

    public static final int HOSTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object hostName_;
    /**
     * <code>string hostName = 3;</code>
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      }
    }
    /**
     * <code>string hostName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNKID_FIELD_NUMBER = 4;
    private int chunkId_;
    /**
     * <code>int32 chunkId = 4;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    public static final int REQTYPEREAD_FIELD_NUMBER = 5;
    private volatile java.lang.Object reqtyperead_;
    /**
     * <code>string reqtyperead = 5;</code>
     */
    public java.lang.String getReqtyperead() {
      java.lang.Object ref = reqtyperead_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqtyperead_ = s;
        return s;
      }
    }
    /**
     * <code>string reqtyperead = 5;</code>
     */
    public com.google.protobuf.ByteString
        getReqtypereadBytes() {
      java.lang.Object ref = reqtyperead_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqtyperead_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReadfileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, readfileName_);
      }
      if (!readchunkdata_.isEmpty()) {
        output.writeBytes(2, readchunkdata_);
      }
      if (!getHostNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hostName_);
      }
      if (chunkId_ != 0) {
        output.writeInt32(4, chunkId_);
      }
      if (!getReqtypereadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, reqtyperead_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReadfileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, readfileName_);
      }
      if (!readchunkdata_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, readchunkdata_);
      }
      if (!getHostNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hostName_);
      }
      if (chunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chunkId_);
      }
      if (!getReqtypereadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, reqtyperead_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile other = (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) obj;

      boolean result = true;
      result = result && getReadfileName()
          .equals(other.getReadfileName());
      result = result && getReadchunkdata()
          .equals(other.getReadchunkdata());
      result = result && getHostName()
          .equals(other.getHostName());
      result = result && (getChunkId()
          == other.getChunkId());
      result = result && getReqtyperead()
          .equals(other.getReqtyperead());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + READFILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getReadfileName().hashCode();
      hash = (37 * hash) + READCHUNKDATA_FIELD_NUMBER;
      hash = (53 * hash) + getReadchunkdata().hashCode();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostName().hashCode();
      hash = (37 * hash) + CHUNKID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId();
      hash = (37 * hash) + REQTYPEREAD_FIELD_NUMBER;
      hash = (53 * hash) + getReqtyperead().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RetrieveFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RetrieveFile)
        edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_RetrieveFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_RetrieveFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.class, edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        readfileName_ = "";

        readchunkdata_ = com.google.protobuf.ByteString.EMPTY;

        hostName_ = "";

        chunkId_ = 0;

        reqtyperead_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_RetrieveFile_descriptor;
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile build() {
        edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile buildPartial() {
        edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile result = new edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile(this);
        result.readfileName_ = readfileName_;
        result.readchunkdata_ = readchunkdata_;
        result.hostName_ = hostName_;
        result.chunkId_ = chunkId_;
        result.reqtyperead_ = reqtyperead_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) {
          return mergeFrom((edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile other) {
        if (other == edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance()) return this;
        if (!other.getReadfileName().isEmpty()) {
          readfileName_ = other.readfileName_;
          onChanged();
        }
        if (other.getReadchunkdata() != com.google.protobuf.ByteString.EMPTY) {
          setReadchunkdata(other.getReadchunkdata());
        }
        if (!other.getHostName().isEmpty()) {
          hostName_ = other.hostName_;
          onChanged();
        }
        if (other.getChunkId() != 0) {
          setChunkId(other.getChunkId());
        }
        if (!other.getReqtyperead().isEmpty()) {
          reqtyperead_ = other.reqtyperead_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object readfileName_ = "";
      /**
       * <code>string readfileName = 1;</code>
       */
      public java.lang.String getReadfileName() {
        java.lang.Object ref = readfileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          readfileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string readfileName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReadfileNameBytes() {
        java.lang.Object ref = readfileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          readfileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string readfileName = 1;</code>
       */
      public Builder setReadfileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        readfileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string readfileName = 1;</code>
       */
      public Builder clearReadfileName() {
        
        readfileName_ = getDefaultInstance().getReadfileName();
        onChanged();
        return this;
      }
      /**
       * <code>string readfileName = 1;</code>
       */
      public Builder setReadfileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        readfileName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString readchunkdata_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes readchunkdata = 2;</code>
       */
      public com.google.protobuf.ByteString getReadchunkdata() {
        return readchunkdata_;
      }
      /**
       * <code>bytes readchunkdata = 2;</code>
       */
      public Builder setReadchunkdata(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        readchunkdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes readchunkdata = 2;</code>
       */
      public Builder clearReadchunkdata() {
        
        readchunkdata_ = getDefaultInstance().getReadchunkdata();
        onChanged();
        return this;
      }

      private java.lang.Object hostName_ = "";
      /**
       * <code>string hostName = 3;</code>
       */
      public java.lang.String getHostName() {
        java.lang.Object ref = hostName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hostName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        java.lang.Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostName = 3;</code>
       */
      public Builder setHostName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hostName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 3;</code>
       */
      public Builder clearHostName() {
        
        hostName_ = getDefaultInstance().getHostName();
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 3;</code>
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hostName_ = value;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public Builder setChunkId(int value) {
        
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public Builder clearChunkId() {
        
        chunkId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reqtyperead_ = "";
      /**
       * <code>string reqtyperead = 5;</code>
       */
      public java.lang.String getReqtyperead() {
        java.lang.Object ref = reqtyperead_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqtyperead_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reqtyperead = 5;</code>
       */
      public com.google.protobuf.ByteString
          getReqtypereadBytes() {
        java.lang.Object ref = reqtyperead_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqtyperead_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqtyperead = 5;</code>
       */
      public Builder setReqtyperead(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqtyperead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqtyperead = 5;</code>
       */
      public Builder clearReqtyperead() {
        
        reqtyperead_ = getDefaultInstance().getReqtyperead();
        onChanged();
        return this;
      }
      /**
       * <code>string reqtyperead = 5;</code>
       */
      public Builder setReqtypereadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqtyperead_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RetrieveFile)
    }

    // @@protoc_insertion_point(class_scope:RetrieveFile)
    private static final edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile();
    }

    public static edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RetrieveFile>
        PARSER = new com.google.protobuf.AbstractParser<RetrieveFile>() {
      public RetrieveFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RetrieveFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RetrieveFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RetrieveFile> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StorageMessagePBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StorageMessagePB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    boolean hasStoreChunkMsg();
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk getStoreChunkMsg();
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunkOrBuilder getStoreChunkMsgOrBuilder();

    /**
     * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
     */
    boolean hasRetrieveChunkFileMsg();
    /**
     * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
     */
    edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile getRetrieveChunkFileMsg();
    /**
     * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
     */
    edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFileOrBuilder getRetrieveChunkFileMsgOrBuilder();

    public edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code StorageMessagePB}
   */
  public  static final class StorageMessagePB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StorageMessagePB)
      StorageMessagePBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StorageMessagePB.newBuilder() to construct.
    private StorageMessagePB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StorageMessagePB() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StorageMessagePB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StorageMessagePB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StorageMessagePB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB.class, edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      STORECHUNKMSG(1),
      RETRIEVECHUNKFILEMSG(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return STORECHUNKMSG;
          case 2: return RETRIEVECHUNKFILEMSG;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int STORECHUNKMSG_FIELD_NUMBER = 1;
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    public boolean hasStoreChunkMsg() {
      return msgCase_ == 1;
    }
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk getStoreChunkMsg() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_;
      }
      return edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance();
    }
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunkOrBuilder getStoreChunkMsgOrBuilder() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_;
      }
      return edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance();
    }

    public static final int RETRIEVECHUNKFILEMSG_FIELD_NUMBER = 2;
    /**
     * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
     */
    public boolean hasRetrieveChunkFileMsg() {
      return msgCase_ == 2;
    }
    /**
     * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
     */
    public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile getRetrieveChunkFileMsg() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_;
      }
      return edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance();
    }
    /**
     * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
     */
    public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFileOrBuilder getRetrieveChunkFileMsgOrBuilder() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_;
      }
      return edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB other = (edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB) obj;

      boolean result = true;
      result = result && getMsgCase().equals(
          other.getMsgCase());
      if (!result) return false;
      switch (msgCase_) {
        case 1:
          result = result && getStoreChunkMsg()
              .equals(other.getStoreChunkMsg());
          break;
        case 2:
          result = result && getRetrieveChunkFileMsg()
              .equals(other.getRetrieveChunkFileMsg());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + STORECHUNKMSG_FIELD_NUMBER;
          hash = (53 * hash) + getStoreChunkMsg().hashCode();
          break;
        case 2:
          hash = (37 * hash) + RETRIEVECHUNKFILEMSG_FIELD_NUMBER;
          hash = (53 * hash) + getRetrieveChunkFileMsg().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StorageMessagePB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StorageMessagePB)
        edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StorageMessagePB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StorageMessagePB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB.class, edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.internal_static_StorageMessagePB_descriptor;
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB build() {
        edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB buildPartial() {
        edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB result = new edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB(this);
        if (msgCase_ == 1) {
          if (storeChunkMsgBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = storeChunkMsgBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (retrieveChunkFileMsgBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = retrieveChunkFileMsgBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB) {
          return mergeFrom((edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB other) {
        if (other == edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case STORECHUNKMSG: {
            mergeStoreChunkMsg(other.getStoreChunkMsg());
            break;
          }
          case RETRIEVECHUNKFILEMSG: {
            mergeRetrieveChunkFileMsg(other.getRetrieveChunkFileMsg());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk, edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.Builder, edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunkOrBuilder> storeChunkMsgBuilder_;
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public boolean hasStoreChunkMsg() {
        return msgCase_ == 1;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk getStoreChunkMsg() {
        if (storeChunkMsgBuilder_ == null) {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_;
          }
          return edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return storeChunkMsgBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance();
        }
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public Builder setStoreChunkMsg(edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk value) {
        if (storeChunkMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          storeChunkMsgBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public Builder setStoreChunkMsg(
          edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.Builder builderForValue) {
        if (storeChunkMsgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          storeChunkMsgBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public Builder mergeStoreChunkMsg(edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk value) {
        if (storeChunkMsgBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.newBuilder((edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            storeChunkMsgBuilder_.mergeFrom(value);
          }
          storeChunkMsgBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public Builder clearStoreChunkMsg() {
        if (storeChunkMsgBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          storeChunkMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.Builder getStoreChunkMsgBuilder() {
        return getStoreChunkMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunkOrBuilder getStoreChunkMsgOrBuilder() {
        if ((msgCase_ == 1) && (storeChunkMsgBuilder_ != null)) {
          return storeChunkMsgBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_;
          }
          return edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance();
        }
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk, edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.Builder, edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunkOrBuilder> 
          getStoreChunkMsgFieldBuilder() {
        if (storeChunkMsgBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.getDefaultInstance();
          }
          storeChunkMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk, edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk.Builder, edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunkOrBuilder>(
                  (edu.usfca.cs.dfs.storage.StorageProtobuf.StoreChunk) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return storeChunkMsgBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile, edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.Builder, edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFileOrBuilder> retrieveChunkFileMsgBuilder_;
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      public boolean hasRetrieveChunkFileMsg() {
        return msgCase_ == 2;
      }
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile getRetrieveChunkFileMsg() {
        if (retrieveChunkFileMsgBuilder_ == null) {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_;
          }
          return edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return retrieveChunkFileMsgBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance();
        }
      }
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      public Builder setRetrieveChunkFileMsg(edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile value) {
        if (retrieveChunkFileMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          retrieveChunkFileMsgBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      public Builder setRetrieveChunkFileMsg(
          edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.Builder builderForValue) {
        if (retrieveChunkFileMsgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          retrieveChunkFileMsgBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      public Builder mergeRetrieveChunkFileMsg(edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile value) {
        if (retrieveChunkFileMsgBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.newBuilder((edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            retrieveChunkFileMsgBuilder_.mergeFrom(value);
          }
          retrieveChunkFileMsgBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      public Builder clearRetrieveChunkFileMsg() {
        if (retrieveChunkFileMsgBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          retrieveChunkFileMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.Builder getRetrieveChunkFileMsgBuilder() {
        return getRetrieveChunkFileMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFileOrBuilder getRetrieveChunkFileMsgOrBuilder() {
        if ((msgCase_ == 2) && (retrieveChunkFileMsgBuilder_ != null)) {
          return retrieveChunkFileMsgBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_;
          }
          return edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance();
        }
      }
      /**
       * <code>.RetrieveFile retrieveChunkFileMsg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile, edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.Builder, edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFileOrBuilder> 
          getRetrieveChunkFileMsgFieldBuilder() {
        if (retrieveChunkFileMsgBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.getDefaultInstance();
          }
          retrieveChunkFileMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile, edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile.Builder, edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFileOrBuilder>(
                  (edu.usfca.cs.dfs.storage.StorageProtobuf.RetrieveFile) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return retrieveChunkFileMsgBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StorageMessagePB)
    }

    // @@protoc_insertion_point(class_scope:StorageMessagePB)
    private static final edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB();
    }

    public static edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StorageMessagePB>
        PARSER = new com.google.protobuf.AbstractParser<StorageMessagePB>() {
      public StorageMessagePB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StorageMessagePB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StorageMessagePB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StorageMessagePB> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.storage.StorageProtobuf.StorageMessagePB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StoreChunk_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StoreChunk_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RetrieveFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RetrieveFile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StorageMessagePB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StorageMessagePB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026storage_protobuf.proto\"y\n\nStoreChunk\022\032" +
      "\n\022writefilechunkName\030\001 \001(\t\022\017\n\007chunkId\030\002 " +
      "\001(\005\022\026\n\016writechunkdata\030\003 \001(\014\022\020\n\010hostName\030" +
      "\004 \001(\t\022\024\n\014reqtypewrite\030\005 \001(\t\"s\n\014RetrieveF" +
      "ile\022\024\n\014readfileName\030\001 \001(\t\022\025\n\rreadchunkda" +
      "ta\030\002 \001(\014\022\020\n\010hostName\030\003 \001(\t\022\017\n\007chunkId\030\004 " +
      "\001(\005\022\023\n\013reqtyperead\030\005 \001(\t\"n\n\020StorageMessa" +
      "gePB\022$\n\rstoreChunkMsg\030\001 \001(\0132\013.StoreChunk" +
      "H\000\022-\n\024retrieveChunkFileMsg\030\002 \001(\0132\r.Retri" +
      "eveFileH\000B\005\n\003msgB\032\n\030edu.usfca.cs.dfs.sto",
      "rageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StoreChunk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StoreChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StoreChunk_descriptor,
        new java.lang.String[] { "WritefilechunkName", "ChunkId", "Writechunkdata", "HostName", "Reqtypewrite", });
    internal_static_RetrieveFile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RetrieveFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RetrieveFile_descriptor,
        new java.lang.String[] { "ReadfileName", "Readchunkdata", "HostName", "ChunkId", "Reqtyperead", });
    internal_static_StorageMessagePB_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StorageMessagePB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StorageMessagePB_descriptor,
        new java.lang.String[] { "StoreChunkMsg", "RetrieveChunkFileMsg", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
