package edu.usfca.cs.dfs.controller;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_heartbeat.proto

public final class ProtoHeartbeat {
  private ProtoHeartbeat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StorageHearbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StorageHearbeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string chunkName = 1;</code>
     */
    String getChunkName();
    /**
     * <code>string chunkName = 1;</code>
     */
    com.google.protobuf.ByteString
        getChunkNameBytes();

    /**
     * <code>string hostName = 2;</code>
     */
    String getHostName();
    /**
     * <code>string hostName = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostNameBytes();

    /**
     * <code>int32 portnum = 3;</code>
     */
    int getPortnum();

    /**
     * <code>int32 chunkId = 4;</code>
     */
    int getChunkId();
  }
  /**
   * Protobuf type {@code StorageHearbeat}
   */
  public  static final class StorageHearbeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StorageHearbeat)
      StorageHearbeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StorageHearbeat.newBuilder() to construct.
    private StorageHearbeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StorageHearbeat() {
      chunkName_ = "";
      hostName_ = "";
      portnum_ = 0;
      chunkId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StorageHearbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              chunkName_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              hostName_ = s;
              break;
            }
            case 24: {

              portnum_ = input.readInt32();
              break;
            }
            case 32: {

              chunkId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoHeartbeat.internal_static_StorageHearbeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoHeartbeat.internal_static_StorageHearbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoHeartbeat.StorageHearbeat.class, ProtoHeartbeat.StorageHearbeat.Builder.class);
    }

    public static final int CHUNKNAME_FIELD_NUMBER = 1;
    private volatile Object chunkName_;
    /**
     * <code>string chunkName = 1;</code>
     */
    public String getChunkName() {
      Object ref = chunkName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        chunkName_ = s;
        return s;
      }
    }
    /**
     * <code>string chunkName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChunkNameBytes() {
      Object ref = chunkName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        chunkName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOSTNAME_FIELD_NUMBER = 2;
    private volatile Object hostName_;
    /**
     * <code>string hostName = 2;</code>
     */
    public String getHostName() {
      Object ref = hostName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      }
    }
    /**
     * <code>string hostName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORTNUM_FIELD_NUMBER = 3;
    private int portnum_;
    /**
     * <code>int32 portnum = 3;</code>
     */
    public int getPortnum() {
      return portnum_;
    }

    public static final int CHUNKID_FIELD_NUMBER = 4;
    private int chunkId_;
    /**
     * <code>int32 chunkId = 4;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getChunkNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chunkName_);
      }
      if (!getHostNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hostName_);
      }
      if (portnum_ != 0) {
        output.writeInt32(3, portnum_);
      }
      if (chunkId_ != 0) {
        output.writeInt32(4, chunkId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getChunkNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chunkName_);
      }
      if (!getHostNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hostName_);
      }
      if (portnum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, portnum_);
      }
      if (chunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chunkId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoHeartbeat.StorageHearbeat)) {
        return super.equals(obj);
      }
      ProtoHeartbeat.StorageHearbeat other = (ProtoHeartbeat.StorageHearbeat) obj;

      boolean result = true;
      result = result && getChunkName()
          .equals(other.getChunkName());
      result = result && getHostName()
          .equals(other.getHostName());
      result = result && (getPortnum()
          == other.getPortnum());
      result = result && (getChunkId()
          == other.getChunkId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHUNKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getChunkName().hashCode();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostName().hashCode();
      hash = (37 * hash) + PORTNUM_FIELD_NUMBER;
      hash = (53 * hash) + getPortnum();
      hash = (37 * hash) + CHUNKID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoHeartbeat.StorageHearbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoHeartbeat.StorageHearbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoHeartbeat.StorageHearbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoHeartbeat.StorageHearbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoHeartbeat.StorageHearbeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StorageHearbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StorageHearbeat)
        ProtoHeartbeat.StorageHearbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoHeartbeat.internal_static_StorageHearbeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoHeartbeat.internal_static_StorageHearbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoHeartbeat.StorageHearbeat.class, ProtoHeartbeat.StorageHearbeat.Builder.class);
      }

      // Construct using ProtoHeartbeat.StorageHearbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chunkName_ = "";

        hostName_ = "";

        portnum_ = 0;

        chunkId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoHeartbeat.internal_static_StorageHearbeat_descriptor;
      }

      public ProtoHeartbeat.StorageHearbeat getDefaultInstanceForType() {
        return ProtoHeartbeat.StorageHearbeat.getDefaultInstance();
      }

      public ProtoHeartbeat.StorageHearbeat build() {
        ProtoHeartbeat.StorageHearbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoHeartbeat.StorageHearbeat buildPartial() {
        ProtoHeartbeat.StorageHearbeat result = new ProtoHeartbeat.StorageHearbeat(this);
        result.chunkName_ = chunkName_;
        result.hostName_ = hostName_;
        result.portnum_ = portnum_;
        result.chunkId_ = chunkId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoHeartbeat.StorageHearbeat) {
          return mergeFrom((ProtoHeartbeat.StorageHearbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoHeartbeat.StorageHearbeat other) {
        if (other == ProtoHeartbeat.StorageHearbeat.getDefaultInstance()) return this;
        if (!other.getChunkName().isEmpty()) {
          chunkName_ = other.chunkName_;
          onChanged();
        }
        if (!other.getHostName().isEmpty()) {
          hostName_ = other.hostName_;
          onChanged();
        }
        if (other.getPortnum() != 0) {
          setPortnum(other.getPortnum());
        }
        if (other.getChunkId() != 0) {
          setChunkId(other.getChunkId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoHeartbeat.StorageHearbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoHeartbeat.StorageHearbeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object chunkName_ = "";
      /**
       * <code>string chunkName = 1;</code>
       */
      public String getChunkName() {
        Object ref = chunkName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          chunkName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string chunkName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getChunkNameBytes() {
        Object ref = chunkName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          chunkName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chunkName = 1;</code>
       */
      public Builder setChunkName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        chunkName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string chunkName = 1;</code>
       */
      public Builder clearChunkName() {

        chunkName_ = getDefaultInstance().getChunkName();
        onChanged();
        return this;
      }
      /**
       * <code>string chunkName = 1;</code>
       */
      public Builder setChunkNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        chunkName_ = value;
        onChanged();
        return this;
      }

      private Object hostName_ = "";
      /**
       * <code>string hostName = 2;</code>
       */
      public String getHostName() {
        Object ref = hostName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder setHostName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        hostName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder clearHostName() {

        hostName_ = getDefaultInstance().getHostName();
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        hostName_ = value;
        onChanged();
        return this;
      }

      private int portnum_ ;
      /**
       * <code>int32 portnum = 3;</code>
       */
      public int getPortnum() {
        return portnum_;
      }
      /**
       * <code>int32 portnum = 3;</code>
       */
      public Builder setPortnum(int value) {

        portnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 portnum = 3;</code>
       */
      public Builder clearPortnum() {

        portnum_ = 0;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public Builder setChunkId(int value) {

        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkId = 4;</code>
       */
      public Builder clearChunkId() {

        chunkId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StorageHearbeat)
    }

    // @@protoc_insertion_point(class_scope:StorageHearbeat)
    private static final ProtoHeartbeat.StorageHearbeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoHeartbeat.StorageHearbeat();
    }

    public static ProtoHeartbeat.StorageHearbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StorageHearbeat>
        PARSER = new com.google.protobuf.AbstractParser<StorageHearbeat>() {
      public StorageHearbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StorageHearbeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StorageHearbeat> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StorageHearbeat> getParserForType() {
      return PARSER;
    }

    public ProtoHeartbeat.StorageHearbeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControllerMessagePBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ControllerMessagePB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.StorageHearbeat storageHeartBeat = 1;</code>
     */
    boolean hasStorageHeartBeat();
    /**
     * <code>.StorageHearbeat storageHeartBeat = 1;</code>
     */
    ProtoHeartbeat.StorageHearbeat getStorageHeartBeat();
    /**
     * <code>.StorageHearbeat storageHeartBeat = 1;</code>
     */
    ProtoHeartbeat.StorageHearbeatOrBuilder getStorageHeartBeatOrBuilder();

    public ProtoHeartbeat.ControllerMessagePB.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code ControllerMessagePB}
   */
  public  static final class ControllerMessagePB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ControllerMessagePB)
      ControllerMessagePBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControllerMessagePB.newBuilder() to construct.
    private ControllerMessagePB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControllerMessagePB() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ControllerMessagePB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtoHeartbeat.StorageHearbeat.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((ProtoHeartbeat.StorageHearbeat) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(ProtoHeartbeat.StorageHearbeat.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtoHeartbeat.StorageHearbeat) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoHeartbeat.internal_static_ControllerMessagePB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoHeartbeat.internal_static_ControllerMessagePB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoHeartbeat.ControllerMessagePB.class, ProtoHeartbeat.ControllerMessagePB.Builder.class);
    }

    private int msgCase_ = 0;
    private Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      STORAGEHEARTBEAT(1),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return STORAGEHEARTBEAT;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int STORAGEHEARTBEAT_FIELD_NUMBER = 1;
    /**
     * <code>.StorageHearbeat storageHeartBeat = 1;</code>
     */
    public boolean hasStorageHeartBeat() {
      return msgCase_ == 1;
    }
    /**
     * <code>.StorageHearbeat storageHeartBeat = 1;</code>
     */
    public ProtoHeartbeat.StorageHearbeat getStorageHeartBeat() {
      if (msgCase_ == 1) {
         return (ProtoHeartbeat.StorageHearbeat) msg_;
      }
      return ProtoHeartbeat.StorageHearbeat.getDefaultInstance();
    }
    /**
     * <code>.StorageHearbeat storageHeartBeat = 1;</code>
     */
    public ProtoHeartbeat.StorageHearbeatOrBuilder getStorageHeartBeatOrBuilder() {
      if (msgCase_ == 1) {
         return (ProtoHeartbeat.StorageHearbeat) msg_;
      }
      return ProtoHeartbeat.StorageHearbeat.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (ProtoHeartbeat.StorageHearbeat) msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (ProtoHeartbeat.StorageHearbeat) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoHeartbeat.ControllerMessagePB)) {
        return super.equals(obj);
      }
      ProtoHeartbeat.ControllerMessagePB other = (ProtoHeartbeat.ControllerMessagePB) obj;

      boolean result = true;
      result = result && getMsgCase().equals(
          other.getMsgCase());
      if (!result) return false;
      switch (msgCase_) {
        case 1:
          result = result && getStorageHeartBeat()
              .equals(other.getStorageHeartBeat());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + STORAGEHEARTBEAT_FIELD_NUMBER;
          hash = (53 * hash) + getStorageHeartBeat().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoHeartbeat.ControllerMessagePB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoHeartbeat.ControllerMessagePB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoHeartbeat.ControllerMessagePB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ControllerMessagePB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ControllerMessagePB)
        ProtoHeartbeat.ControllerMessagePBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoHeartbeat.internal_static_ControllerMessagePB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoHeartbeat.internal_static_ControllerMessagePB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoHeartbeat.ControllerMessagePB.class, ProtoHeartbeat.ControllerMessagePB.Builder.class);
      }

      // Construct using ProtoHeartbeat.ControllerMessagePB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoHeartbeat.internal_static_ControllerMessagePB_descriptor;
      }

      public ProtoHeartbeat.ControllerMessagePB getDefaultInstanceForType() {
        return ProtoHeartbeat.ControllerMessagePB.getDefaultInstance();
      }

      public ProtoHeartbeat.ControllerMessagePB build() {
        ProtoHeartbeat.ControllerMessagePB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoHeartbeat.ControllerMessagePB buildPartial() {
        ProtoHeartbeat.ControllerMessagePB result = new ProtoHeartbeat.ControllerMessagePB(this);
        if (msgCase_ == 1) {
          if (storageHeartBeatBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = storageHeartBeatBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoHeartbeat.ControllerMessagePB) {
          return mergeFrom((ProtoHeartbeat.ControllerMessagePB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoHeartbeat.ControllerMessagePB other) {
        if (other == ProtoHeartbeat.ControllerMessagePB.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case STORAGEHEARTBEAT: {
            mergeStorageHeartBeat(other.getStorageHeartBeat());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoHeartbeat.ControllerMessagePB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoHeartbeat.ControllerMessagePB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoHeartbeat.StorageHearbeat, ProtoHeartbeat.StorageHearbeat.Builder, ProtoHeartbeat.StorageHearbeatOrBuilder> storageHeartBeatBuilder_;
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      public boolean hasStorageHeartBeat() {
        return msgCase_ == 1;
      }
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      public ProtoHeartbeat.StorageHearbeat getStorageHeartBeat() {
        if (storageHeartBeatBuilder_ == null) {
          if (msgCase_ == 1) {
            return (ProtoHeartbeat.StorageHearbeat) msg_;
          }
          return ProtoHeartbeat.StorageHearbeat.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return storageHeartBeatBuilder_.getMessage();
          }
          return ProtoHeartbeat.StorageHearbeat.getDefaultInstance();
        }
      }
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      public Builder setStorageHeartBeat(ProtoHeartbeat.StorageHearbeat value) {
        if (storageHeartBeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          storageHeartBeatBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      public Builder setStorageHeartBeat(
          ProtoHeartbeat.StorageHearbeat.Builder builderForValue) {
        if (storageHeartBeatBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          storageHeartBeatBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      public Builder mergeStorageHeartBeat(ProtoHeartbeat.StorageHearbeat value) {
        if (storageHeartBeatBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != ProtoHeartbeat.StorageHearbeat.getDefaultInstance()) {
            msg_ = ProtoHeartbeat.StorageHearbeat.newBuilder((ProtoHeartbeat.StorageHearbeat) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            storageHeartBeatBuilder_.mergeFrom(value);
          }
          storageHeartBeatBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      public Builder clearStorageHeartBeat() {
        if (storageHeartBeatBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          storageHeartBeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      public ProtoHeartbeat.StorageHearbeat.Builder getStorageHeartBeatBuilder() {
        return getStorageHeartBeatFieldBuilder().getBuilder();
      }
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      public ProtoHeartbeat.StorageHearbeatOrBuilder getStorageHeartBeatOrBuilder() {
        if ((msgCase_ == 1) && (storageHeartBeatBuilder_ != null)) {
          return storageHeartBeatBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (ProtoHeartbeat.StorageHearbeat) msg_;
          }
          return ProtoHeartbeat.StorageHearbeat.getDefaultInstance();
        }
      }
      /**
       * <code>.StorageHearbeat storageHeartBeat = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoHeartbeat.StorageHearbeat, ProtoHeartbeat.StorageHearbeat.Builder, ProtoHeartbeat.StorageHearbeatOrBuilder>
          getStorageHeartBeatFieldBuilder() {
        if (storageHeartBeatBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = ProtoHeartbeat.StorageHearbeat.getDefaultInstance();
          }
          storageHeartBeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoHeartbeat.StorageHearbeat, ProtoHeartbeat.StorageHearbeat.Builder, ProtoHeartbeat.StorageHearbeatOrBuilder>(
                  (ProtoHeartbeat.StorageHearbeat) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return storageHeartBeatBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ControllerMessagePB)
    }

    // @@protoc_insertion_point(class_scope:ControllerMessagePB)
    private static final ProtoHeartbeat.ControllerMessagePB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoHeartbeat.ControllerMessagePB();
    }

    public static ProtoHeartbeat.ControllerMessagePB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControllerMessagePB>
        PARSER = new com.google.protobuf.AbstractParser<ControllerMessagePB>() {
      public ControllerMessagePB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ControllerMessagePB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControllerMessagePB> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ControllerMessagePB> getParserForType() {
      return PARSER;
    }

    public ProtoHeartbeat.ControllerMessagePB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StorageHearbeat_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StorageHearbeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ControllerMessagePB_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ControllerMessagePB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025proto_heartbeat.proto\"X\n\017StorageHearbe" +
      "at\022\021\n\tchunkName\030\001 \001(\t\022\020\n\010hostName\030\002 \001(\t\022" +
      "\017\n\007portnum\030\003 \001(\005\022\017\n\007chunkId\030\004 \001(\005\"J\n\023Con" +
      "trollerMessagePB\022,\n\020storageHeartBeat\030\001 \001" +
      "(\0132\020.StorageHearbeatH\000B\005\n\003msgb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StorageHearbeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StorageHearbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StorageHearbeat_descriptor,
        new String[] { "ChunkName", "HostName", "Portnum", "ChunkId", });
    internal_static_ControllerMessagePB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ControllerMessagePB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ControllerMessagePB_descriptor,
        new String[] { "StorageHeartBeat", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
